know={
    "hlo" : "Hii...Krishna This Side...!<br>How Can I Help You..?",
    "hello" : "Hii...Krishna This Side...!<br>How Can I Help You..?",
    "HELLO" : "Hii...Krishna This Side...!<br>How Can I Help You..?",
    "Hlo" : "Hii...Krishna This Side...!<br>How Can I Help You..?",
    "HLO" : "Hii...Krishna This Side...!<br>How Can I Help You..?",
    "hey" : "Hii...Krishna This Side...!<br>How Can I Help You..?",
    "hyy" : "Hii...Krishna This Side...!<br>How Can I Help You..?",
    "hy" : "Hii...Krishna This Side...!<br>How Can I Help You..?",
    "HEY" : "Hii...Krishna This Side...!<br>How Can I Help You..?",
    "HY" : "Hii...Krishna This Side...!<br>How Can I Help You..?",
    "HYY" : "Hii...Krishna This Side...!<br>How Can I Help You..?",
    "Hy" : "Hii...Krishna This Side...!<br>How Can I Help You..?",
    "Hyy" : "Hii...Krishna This Side...!<br>How Can I Help You..?",
    "hi" : "Hii...Krishna This Side...!<br>How Can I Help You..?",
    "hii" : "Hii...Krishna This Side...!<br>How Can I Help You..?",
    "hiii" : "Hii...Krishna This Side...!<br>How Can I Help You..?",
    "Hi" : "Hii...Krishna This Side...!<br>How Can I Help You..?",
    "Hii" : "Hii...Krishna This Side...!<br>How Can I Help You..?",
    "Hiii" : "Hii...Krishna This Side...!<br>How Can I Help You..?",
    "How Are You" : "I Am Fine Sir.<br>How's You..?",
    "how are you" : "I Am Fine Sir.<br>How's You..?",
    "How are you" : "I Am Fine Sir.<br>How's You..?",
    "HOW ARE YOU" : "I Am Fine Sir.<br>How's You..?",
    "fine" : "Welldone.",
    "i am fine" : "Welldone.",
    "i am also fine" : "Welldone.",
    "Fine" : "Welldone.",
    "good" : "Welldone.",
    "i am good" : "Welldone.",
    "Good" : "Welldone.",
    "computer" : "Full Form Of Computer Is -<br>C - Common<br>O - Operating<br>M - Machine<br>P - Purposely<br>U - Used For<br>T - Technological<br>E - Educational<br>R - Research.",
    "Computer" : "Full Form Of Computer Is -<br>C - Common<br>O - Operating<br>M - Machine<br>P - Purposely<br>U - Used For<br>T - Technological<br>E - Educational<br>R - Research.",
    "COMPUTER" : "Full Form Of Computer Is -<br>C - Common<br>O - Operating<br>M - Machine<br>P - Purposely<br>U - Used For<br>T - Technological<br>E - Educational<br>R - Research.",
    "what is full form of computer" : "Full Form Of Computer Is -<br>C - Common<br>O - Operating<br>M - Machine<br>P - Purposely<br>U - Used For<br>T - Technological<br>E - Educational<br>R - Research.",
    "full form of computer" : "Full Form Of Computer Is -<br>C - Common<br>O - Operating<br>M - Machine<br>P - Purposely<br>U - Used For<br>T - Technological<br>E - Educational<br>R - Research.",
    "computer full form" : "Full Form Of Computer Is -<br>C - Common<br>O - Operating<br>M - Machine<br>P - Purposely<br>U - Used For<br>T - Technological<br>E - Educational<br>R - Research.",
    "father of computer" : "The Father Of Computer Is - 'Charles Babbage'<br>Born In - 26 December 1791. London, United Kingdom.<br>Died In - 18 october 1871. Marylebone, London, United Kingdom.<br>known For - Difference Engine.<br>Awards - Gold Madel Of The Royal Astronomical Society, 1824.<br>Fields - Mathematics, Engineering, Political Economy, Computer Science.<br>wife - Georgiana Whitmore<br>(Married 1814, Died 1827).",
    "Father of computer" : "The Father Of Computer Is - 'Charles Babbage'<br>Born In - 26 December 1791. London, United Kingdom.<br>Died In - 18 october 1871. Marylebone, London, United Kingdom.<br>known For - Difference Engine.<br>Awards - Gold Madel Of The Royal Astronomical Society, 1824.<br>Fields - Mathematics, Engineering, Political Economy, Computer Science.<br>wife - Georgiana Whitmore<br>(Married 1814, Died 1827).",
    "mother of computer" : "The Mother Of Computer Is - 'Ada Lovelace'<br>Born In - 10 December 1815, London, United Kingdom.<br>Died In - 27 November 1852, London, United Kingdom.<br>Known For - Mathematics, Computing.",
    "Mother of computer" : "The Mother Of Computer Is - 'Ada Lovelace'<br>Born In - 10 December 1815, London, United Kingdom.<br>Died In - 27 November 1852, London, United Kingdom.<br>Known For - Mathematics, Computing.",
    "c language" : "C is a General-Purpose Programming Language.<br>Created By - 'Dennis Ritchie' Of The 'Bell Laboratories' in '1972'.<br>File Extention - .c.",
    "C language" : "C is a General-Purpose Programming Language.<br>Created By - 'Dennis Ritchie' Of The 'Bell Laboratories' in '1972'.<br>File Extention - .c.",
    "c++" : "C++ is a High-Level Programming Language.<br>Created By - 'Bjarne Stroustrup' Of The 'Bell Laboratories' in '1979'.<br>File Extention - .c++.",
    "C++" : "C++ is a High-Level Programming Language.<br>Created By - 'Bjarne Stroustrup' Of The 'Bell Laboratories' in '1979'.<br>File Extention - .c++.",
    "java" : "Java Programming Is 'Simple', 'Robust', 'Portable', 'platform-Independent', 'High-Performance' Language.<br>Develop By - James Gosling(Father Of Java) In 1995.<br>Team Name - 'Green Team'.<br>Team Mambers - 'james Gosling(Leader)', 'Mike Sheridan' and 'Patrick Naughton' Initiated Java Project in June 1991.<br>File Extention - .java.",
    "Java" : "Java Programming Is 'Simple', 'Robust', 'Portable', 'platform-Independent', 'High-Performance' Language.<br>Develop By - James Gosling(Father Of Java) In 1995.<br>Team Name - 'Green Team'.<br>Team Mambers - 'james Gosling(Leader)', 'Mike Sheridan' and 'Patrick Naughton' Initiated Java Project in June 1991.<br>File Extention - .java."
    };